# Generated by Django 4.2.11 on 2025-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('roll', models.PositiveIntegerField()),
                ('pass_by', models.CharField(max_length=100)),
            ],
        ),
    ]
